from selenium.webdriver.common.by import By
import datetime

day_of_m_today = int(datetime.date.today().strftime('%d'))

current_date_loc = (By.CLASS_NAME, 'currentdatelink')
month_button_loc = (By.CLASS_NAME, 'fc-button-month')
month_name_loc = (By.ID, 'dpMonth')
today_day_loc = (By.CLASS_NAME, 'fc-today')
next_loc = (By.CLASS_NAME, 'cal_next')
previous_loc = (By.CLASS_NAME, 'cal_prev')
month_dropdown = (By.CLASS_NAME, 'fc-header-title')
year_loc = (By.XPATH, '(//th[@class="switch"])[251]')
next_year_loc = (By.XPATH, '(//th[@class="next"])[251]')
prev_year_loc = (By.XPATH, '(//th[@class="prev"])[251]')
months_loc = (By.XPATH, '//div[@class="datepicker-months"]/table/tbody/tr/td/span')
years_loc = (By.XPATH, '//div[@class="datepicker-years"]/table/tbody/tr/td/span')

quick_add_loc = (By.ID, 'QuickAddToggle')
workout_lib_loc = (By.ID, 'WorkoutLibAdd')
workout_lib_header_loc = (By.ID, 'WorkoutLibHeader')
workout_lib_activity_type_loc = (By.ID, 'ActivityTypeFilter')
workout_lib_list = (By.ID, 'LibraryList')
calendar_error_loc = (By.CLASS_NAME, 'alert-error')
save_to_lib_success_alert_loc = (By.CLASS_NAME, 'alert-success')

completion_button_loc = (By.CLASS_NAME, 'fc-button-colorcodecal')
completion_settings_loc = (By.XPATH, '//a[@data-reveal-id="ColorCompletion"]')
completion_iframe_loc = (By.ID, "ColorCompletioniFrame")
completion_green_settings_1_loc = (By.ID, 'GreenStart')
completion_green_settings_2_loc = (By.ID, 'GreenEnd')
completion_yellow_settings_1_loc = (By.ID, 'YellowStart')
completion_yellow_settings_2_loc = (By.ID, 'YellowEnd')
completion_yellow_ending_loc = (By.ID, 'YellowLowEnding')
completion_yellow_starting_loc = (By.ID, 'YellowHighStarting')
completion_red_low_loc = (By.ID, 'RedLow')
completion_red_high_loc = (By.ID, 'RedHigh')
update_completion_loc = (By.XPATH, '//input[@type="submit"]')

date_field_loc = (By.ID, 'WorkoutDate')
time_field_loc = (By.ID, 'WorkoutTime')
time_list_loc = (By.XPATH, '//ul[@class="ui-timepicker-list picktime"]/li')
activity_type_loc = (By.ID, 'ActivityType')
workout_name_loc = (By.ID, 'Name')
workout_desc_loc = (By.ID, 'Desc')
distance_loc = (By.ID, 'Distance')
distance_type_loc = (By.ID, 'DistType')
duration_loc = (By.ID, 'Duration')
how_feel_loc = (By.ID, 'HowFeel')
perceived_effort_loc = (By.ID, 'PerEffort')
post_workout_notes = (By.ID, 'PostDesc')
add_workout_button_loc = (By.ID, 'saveButton')
workout_in_calendar_loc = (By.XPATH, f'//td[@data-day="{day_of_m_today}"]/div/div/div/div')
workout_color_loc = (By.XPATH, f'//td[@data-day="{day_of_m_today}"]/div/div/div/div/a/div')
workout_menu = (By.XPATH, f'//td[@data-day="{day_of_m_today}"]/div/div/div/div/ul/li')
delete_ok = (By.XPATH, '//a[@data-handler="1"]')
planned_workout_loc = (By.ID, 'PlannedWorkout')
planned_distance_loc = (By.ID, 'PDistance')
planned_dist_type_loc = (By.ID, 'PDistType')
planned_duration_loc = (By.ID, 'PDuration')
mark_as_race_loc = (By.ID, 'IsRace')
overall_place_loc = (By.ID, 'OverallPlace')
age_group_place_loc = (By.ID, 'AgeGroupPlace')
save_to_lib_loc = (By.ID, 'SaveLibrary')

details_activity_type = (By.CLASS_NAME, 'activityTypeName')
details_time_loc = (By.XPATH, '//div[@class="formSep"]/div[1]')
details_workout_name_loc = (By.XPATH, '(//div[@class="formSep"]/div)[3]')
details_workout_desc_loc = (By.CLASS_NAME, 'testme')
details_distance_duration_loc = (By.XPATH, '//div[@class="formSep"]/span[1]')
details_pace_loc = (By.XPATH, '//div[@class="formSep"]/span[2]')
details_felt_loc = (By.XPATH, '(//div[@class="formSep"]/span)[3]')
details_per_effort_loc = (By.XPATH, '(//div[@class="formSep"])[3]')
details_planned_race_res_loc = (By.XPATH, '(//div[@class="formSep"])[2]')
